eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8865
spring:
  application:
    name: service-hi-hystrix
    
feign:
  hystrix:
    enabled: true